### ISSUE TITLE
It does not seem to work for some modification

### ISSUE THREAD

**Issue by steveoriol** [dpi/coi#4]
Hello, I love this module ;-)
It works well with config like 'system.performance' :
If on "settings.php", I had:

```
$config['system.performance']['css']['preprocess'] = 0;
$config['system.performance']['js']['preprocess'] = 0;
```

on .../admin/config/development/performance , the checkboxs are disable and I get the message "This field is overridden by environment specific configuration."

But I use the module "imagemagick", on .../admin/config/media/image-toolkit , you can configure the "Path to the package executables".
on live, I use "/var/www/vhosts/xxxxx.com/opt/ImageMagick/bin/"
and on local "/usr/bin/" by add on "settings.php":

`$config['imagemagick.settings']['path_to_binaries'] = '/usr/bin/';`

"drush config-get imagemagick.settings --include-overridden" is OK, but I always see the "/var/www/vhosts/xxxxx.com/opt/ImageMagick/bin/" without message inside the UI of the local site ??

Do you have an idea why it does not work?

**Comment by steveoriol** [comment]
OK, sorry for that, I thought that the module can recognize all the written configuration by itself.
So I need to create a module for modules that I need to have 2 configurations, _(as you did with the module "[config_override_core_fields](https://www.drupal.org/project/config_override_core_fields)" for the configuration of the heart)_
Thanks again.

**Comment by dpi** [comment]
Duplicated by https://www.drupal.org/project/coi/issues/2967112
